version: 2
updates:
  # Maintain Backend Dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "backend"
      include: "scope"

  # Maintain Frontend Dependencies
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      flutter-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "frontend"

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
