name: orthosense
description: Digital Health telerehabilitation with Hybrid AI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  # Camera & Permissions
  camera: ^0.11.2+1
  permission_handler: ^11.4.0

  connectivity_plus: ^6.1.5
  dio: ^5.4.3+1
  drift: ^2.28.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.24
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.28.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
