name: orthosense
description: Digital Health telerehabilitation application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  camera: ^0.11.1
  connectivity_plus: ^7.0.0
  dio: ^5.4.3+1
  drift: ^2.30.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^10.0.0
  flutter_tts: ^4.2.5
  freezed_annotation: ^3.1.0
  image: ^4.5.4
  image_picker: ^1.0.7
  intl: ^0.20.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  pdf: ^3.11.1
  riverpod_annotation: ^3.0.3
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  sqlite3_flutter_libs: ^0.5.24
  timezone: ^0.10.0
  uuid: ^4.4.0
  video_player: ^2.9.2
  wakelock_plus: ^1.4.0
  google_mlkit_pose_detection: ^0.14.0
  tflite_flutter: ^0.12.1
  video_thumbnail: ^0.5.3
  fl_chart: ^1.1.1


dev_dependencies:
  build_runner: ^2.10.5
  drift_dev: ^2.28.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  patrol: ^4.1.0
  riverpod_generator: ^3.0.3
  very_good_analysis: ^10.0.0

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/exercise_classifier.tflite
