name: orthosense
description: Digital Health telerehabilitation application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  dio: ^5.4.3+1
  drift: ^2.30.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^10.0.0
  flutter_tts: ^4.2.3
  freezed_annotation: ^3.1.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.4
  sqlite3_flutter_libs: ^0.5.24
  uuid: ^4.4.0


dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.30.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.9.5
  riverpod_generator: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
