name: orthosense
description: Digital Health telerehabilitation application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  camera: ^0.11.1
  dio: ^5.4.3+1
  drift: ^2.22.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^10.0.0
  flutter_tts: ^4.2.3
  freezed_annotation: ^3.1.0
  image: ^4.5.4
  image_picker: ^1.0.7
  intl: ^0.20.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  pdf: ^3.11.1
  riverpod_annotation: ^3.0.3
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  sqlite3_flutter_libs: ^0.5.24
  timezone: ^0.10.0
  uuid: ^4.4.0
  video_player: ^2.9.2
  wakelock_plus: ^1.4.0
  google_mlkit_pose_detection: ^0.11.0
  tflite_flutter: ^0.11.0
  video_thumbnail: ^0.5.3
  fl_chart: ^0.69.2


dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.22.1
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^3.0.3
  very_good_analysis: ^10.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/exercise_classifier.tflite
